name: hesap
description: QR kod ile ödeme

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  flutter_svg: ^1.0.3
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  get_it: ^7.2.0
  qr_code_scanner: ^0.7.0
  firebase_storage: ^10.2.17
  connectivity_plus: ^2.3.2
  flutter_credit_card: ^3.0.1
  like_button: ^2.0.4
  animated_icon_button: ^1.0.2
  animated_splash_screen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/restoranlar.json
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu_regular.ttf
          weight: 500
        - asset: assets/fonts/ubuntu_bold.ttf
          weight: 700